---
title: Essays and Stories
timezone: UTC
collections:
  category:
    title: Category
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: category
  values:
    layout: category
email: monkeyx@gmail.com
description: Essays and Stories by Seyed P. Razavi
baseurl: ''
url: https://blog.srazavi.com
twitter_username: monkeyx
github_username: seyedrazavi
author: Seyed P. Razavi
lang: en_GB
remote_theme: thelehhman/plainwhite-jekyll
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
- jekyll-sitemap
- jekyll-remote-theme
excerpt_delimiter: "<!--more-->"
feed:
  path: atom.xml
plainwhite:
  title: Essays and Stories by Seyed P. Razavi
  tagline: Essays and Stories <br/>by Seyed P. Razavi
  date_format: "%b %-d, %Y"
  sitemap: true
  analytics_id: UA-105585443-1
  navigation:
  - title: Home
    url: "/"
  - title: About
    url: https://www.srazavi.com
  social_links:
    linkedIn: in/sprazavi
  disqus_shortname: essays-and-stories-by-seyed-p-razavi
